MA/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('social/', include('social.urls', namespace='social'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from . import views


app_name = 'social'
urlpatterns = [

    path('post_details/', views.show_details, name='post_details'),
    path('update_like/', views.update_like,name='update_like'),
    path('save_post/', views.save_post, name='save_post'),





    ]

social/models.py
from django.db import models


from taggit.managers import TaggableManager
from django_resized import ResizedImageField

from account.models import SocialUser
from .tools import user_art_path

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=64)
    description = models.TextField()
    views = models.IntegerField(default=0)
    tag = TaggableManager()
    likes = models.ManyToManyField(SocialUser, blank=True, related_name='liked_posts', )
    saved_by = models.ManyToManyField(SocialUser, related_name='saved_posts_by', blank=True)
    published_at = models.DateTimeField(auto_now_add=True)
    last_change = models.DateTimeField(auto_now=True)
    auther = models.ForeignKey(SocialUser, related_name="post", on_delete=models.CASCADE,)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-last_change']
        indexes = [
            models.Index(fields=['-last_change',])
        ]


class Arts(models.Model):
    image = ResizedImageField(quality=80, upload_to=user_art_path,size=[500,300])
    post = models.ForeignKey(Post, related_name='images', on_delete=models.CASCADE)
    description = models.TextField(blank=True)


class SoftwareCategory(models.Model):
    name = models.CharField(max_length=128)
    slug = models.SlugField()
    post = models.ForeignKey(Post, related_name='software_categories', on_delete=models.CASCADE)

social/views.py
from django.shortcuts import render,get_object_or_404

from account.models import SocialUser
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from .models import Post
# Create your views here.


def show_details(request):
    post = get_object_or_404(Post, id=1)
    auther = request.user
    print(auther.id)
    print(request.user.id)
    print ('check that auther is equal to request user ',auther == request.user)
    arts = post.images.all()
    print('print profile executed')
    print(auther in post.saved_by.all())
    post.views += 1
    context = {
        'post': post,
        'auther': auther,
        'arts': arts,
        'is_in_auther': auther in post.saved_by.all(),
    }
    print(context['is_in_auther'])
    return render(request, 'views/post_details.html', context=context)


@login_required
@require_POST
def update_like(request):
    if request.method == 'POST':
        post_id = request.POST.get('item_id')
        user = request.user
        if post_id is not None:
            post = get_object_or_404(Post, id=post_id)
            if user in post.likes.all():
                post.likes.remove(user)
            else:
                post.likes.add(user)
            post_likes = post.likes.count()
            response_data = {
                'post_likes': post_likes,
                'success': True,
            }
        else:
            response_data = {'error': 'invalid post', 'success': False}
        return JsonResponse(response_data,)


@require_POST
@login_required
def save_post(request):
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        user = request.user
        if post_id is not None:
            post = get_object_or_404(Post, id=post_id)
            if user in post.saved_by.all():
                post.saved_by.remove(user)
                saved = False
            else:
                post.saved_by.add(user)
                saved = True

            response_data = {
                'saved': saved,
                'success': True,

            }
        else:
            response_data = {'error': 'invalid post', 'success': False}
        print('this is in ajax',user in post.saved_by.all())
        return JsonResponse(response_data)

social/templates/views/post_details.html
{% extends 'parents/base.html' %}
{% load static %}
{% load thumbnail %}
{% block content %}
   <div class="main-container">
       <div class="left ">
           <div class="person-work p-relative">
               <div class="work-box ">
                    <div class="img-box">
                        {% for art in arts %}
                        <img src="{{ art.image.url }}" alt="">
                        <h4 class="work-name">
                        {{ art.description }}
                        </h4>
                        {% endfor %}
                    </div>
               </div>
               <button class="btn-right p-absolut"><i class="fa fa-angle-right"></i></button>
               <button class="btn-left p-absolut"><i class="fa fa-angle-left"></i></button>
           </div>
       </div>
       <div class="right">
           <div class="right-container">
               <div class="profile">
                   <div class="profile-box">
                       <img src="{{ auther.profile }}" alt="">
                       <div class="profile-info">
                           <h1>{{ auther.first_name }} {{ auther.last_name }}</h1>
                           <h4>{{ auther.job }}</h4>
                       </div>
                   </div>
                   <div class="profile-btn">
                       <button class="follow-btn"><i class="fa fa-user-plus"> </i> Follow</button>
                       <button class="touch-btn"><i class="fa fa-handshake-simple"> </i> Get in touch</button>
                   </div>
                   <div class="save-btn" >
                       <button class="save-button" id = 'save_post'>
                           <i class="fa fa-bookmark"></i>
                           {% if is_in_auther  %}
                               unsaved
                           {% else %}
                               save
                           {% endif %}
                       </button>
                   </div>
               </div>
               <div class="post-info" data-item-id = "{{ post.id }}">
                   <div class="description">
                       <div class="explanation">
                           {% if post.description %}
                           <p>
                             {{ post.description }}
                           </p>
                           {% endif %}
                       </div>
                       <div class="time">
                           <i class="fa fa-clock-rotate-left"></i><p>1 days ago</p>
                       </div>
                       <div class="popularity">
                           <h4><i class="fa fa-thumbs-up" id='like_count'>{{ post.likes.count }}</i></h4>
                            <h4><i class="fa fa-eye">1k</i></h4>
                       </div>
                       <div class="social-media">
                           <i class="fa-brands fa-instagram"><a href="#"></a></i>
                           <i class="fa-brands fa-whatsapp"><a href="#"></a></i>
                           <i class="fa-brands fa-x-twitter"><a href="#"></a></i>
                           <i class="fa-brands fa-youtube"><a href="#"></a></i>
                       </div>
                   </div>
               </div>
               <div class="tags">
                   <div class="links">
                       <a href="#">#blender</a>
                       <a href="#">#ibs-paint-x</a>
                       <a href="#">#adobe-photoshop</a>
                       <a href="#">#blender</a>
                       <a href="#">#ibs-paint-x</a>
                       <a href="#">#adobe-photoshop</a>
                   </div>
               </div>
                <div class="more-by-user-title">
                    <h4>more by {{ auther.first_name }} {{ auther.last_name }}</h4>
                </div>
               <div class="more-by-user">
                   <div class="right-img-box">
                       <img src="images/photo_5801136709969231210_y.jpg" alt="">
                   </div>
               </div>
               <button class="report-btn">
                   <i class="fa fa-flag"></i>
                    report
               </button>
           </div>
           </div>
   </div>
<script src="{% static 'js/commends-page.js' %}"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
    $(document).ready(function(){
    $('#like_count').on('click', function(){
        updateQuantity($(this).closest('.post-info').data('item-id'));});
    function updateQuantity(itemId){

        $.ajax({
            type : 'POST',
            url : '{% url 'social:update_like'%}',
            data :{'csrfmiddlewaretoken':'{{ csrf_token }}', 'item_id':itemId,},
            success : function (data) {
                if (data.success) {
                    $('#like_count').text(data.post_likes);
                }
                else {
                    alert('error for updating quantity');
                }
            },
        });
    }
    $(".save-button").click(function (){
        console.log('something happens')
        var postInfoElement = document.querySelector('.post-info');
        var postId = postInfoElement.getAttribute('data-item-id');
        console.log(postId);
            $.ajax({
                type: "POST",
                url: '{% url  'social:save_post' %}',
                data:{'csrfmiddlewaretoken': '{{csrf_token}}','post_id':postId },
                success :function (data) {
                    if (data.saved){
                        $('#save_post').text('unsaved');
                    }
                    else {
                        $('#save_post').text('saved');
                    }
                },
                error :function (error) {
                    console.log(' Ajaxخطا در ارسال درخواست'+error);
                }
            });
        });
});
</script>
{% endblock %}